//! Core types for the evolution system.

use std::fmt;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// ── Curator types ───────────────────────────────────────────────────

/// Skill lifecycle state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SkillState {
    Active,
    Stale,
    Archived,
    Pinned,
}

impl fmt::Display for SkillState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Active => write!(f, "active"),
            Self::Stale => write!(f, "stale"),
            Self::Archived => write!(f, "archived"),
            Self::Pinned => write!(f, "pinned"),
        }
    }
}

/// Where a skill originated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SkillOrigin {
    /// Shipped with the system.
    Bundled,
    /// Auto-generated by the agent.
    Agent,
    /// Installed from the skill hub/registry.
    Hub,
    /// Manually created by the user.
    User,
}

impl fmt::Display for SkillOrigin {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Bundled => write!(f, "bundled"),
            Self::Agent => write!(f, "agent"),
            Self::Hub => write!(f, "hub"),
            Self::User => write!(f, "user"),
        }
    }
}

/// Per-skill usage telemetry tracked by the Curator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillUsage {
    /// Current lifecycle state.
    pub state: SkillState,
    /// Who created this skill.
    pub created_by: SkillOrigin,
    /// Number of times this skill has been used/activated.
    pub use_count: u64,
    /// Number of times the skill content has been viewed.
    pub view_count: u64,
    /// Number of patches applied to this skill.
    pub patch_count: u64,
    /// Timestamp of the last recorded activity.
    pub last_activity_at: DateTime<Utc>,
    /// If true, the skill will never be auto-transitioned.
    pub pinned: bool,
}

impl SkillUsage {
    /// Create a new usage entry with default state.
    pub fn new(created_by: SkillOrigin) -> Self {
        Self {
            state: SkillState::Active,
            created_by,
            use_count: 0,
            view_count: 0,
            patch_count: 0,
            last_activity_at: Utc::now(),
            pinned: false,
        }
    }
}

/// Record of an automatic state transition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Transition {
    pub skill_name: String,
    pub from: SkillState,
    pub to: SkillState,
    pub applied_at: DateTime<Utc>,
}

/// A pair of skills that may be redundant.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MergeCandidate {
    pub skill_a: String,
    pub skill_b: String,
    /// Similarity score between 0.0 and 1.0.
    pub similarity: f64,
    pub reason: String,
}

/// Result of a consolidation scan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConsolidationReport {
    pub merge_candidates: Vec<MergeCandidate>,
    pub skills_scanned: usize,
}

impl ConsolidationReport {
    /// Returns true if no merge candidates were found.
    pub fn is_clean(&self) -> bool {
        self.merge_candidates.is_empty()
    }
}

// ── SkillManager types ──────────────────────────────────────────────

/// Provenance — who created or last modified a skill via SkillManager.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SkillProvenance {
    /// Shipped with the system; not user-editable by default.
    Bundled,
    /// Auto-generated by the agent (e.g. distilled from a conversation).
    Agent,
    /// Manually created or edited by the user.
    User,
}

impl fmt::Display for SkillProvenance {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Bundled => write!(f, "bundled"),
            Self::Agent => write!(f, "agent"),
            Self::User => write!(f, "user"),
        }
    }
}

/// A partial update to apply to an existing skill.
///
/// All fields are optional — only non-`None` fields are applied.
#[derive(Debug, Clone, Default)]
pub struct SkillPatch {
    /// Replace the trigger words list entirely.
    pub trigger_words: Option<Vec<String>>,
    /// Replace the description line.
    pub description: Option<String>,
    /// Replace the full markdown body (after frontmatter).
    pub content: Option<String>,
}

/// The type of operation recorded in SkillManager usage tracking.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum UsageOperation {
    Create,
    Edit,
    Patch,
    Delete,
}

impl fmt::Display for UsageOperation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Create => write!(f, "create"),
            Self::Edit => write!(f, "edit"),
            Self::Patch => write!(f, "patch"),
            Self::Delete => write!(f, "delete"),
        }
    }
}

/// A single usage event recorded to `.usage-log.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageEntry {
    pub skill_name: String,
    pub operation: UsageOperation,
    pub provenance: SkillProvenance,
    pub timestamp: DateTime<Utc>,
}

/// Top-level structure for `.usage-log.json` (SkillManager event log).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SkillUsageLog {
    pub entries: Vec<UsageEntry>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn skill_state_display() {
        assert_eq!(SkillState::Active.to_string(), "active");
        assert_eq!(SkillState::Stale.to_string(), "stale");
        assert_eq!(SkillState::Archived.to_string(), "archived");
        assert_eq!(SkillState::Pinned.to_string(), "pinned");
    }

    #[test]
    fn skill_state_serde_roundtrip() {
        for state in [
            SkillState::Active,
            SkillState::Stale,
            SkillState::Archived,
            SkillState::Pinned,
        ] {
            let json = serde_json::to_string(&state).unwrap();
            let back: SkillState = serde_json::from_str(&json).unwrap();
            assert_eq!(state, back);
        }
    }

    #[test]
    fn skill_origin_display() {
        assert_eq!(SkillOrigin::Bundled.to_string(), "bundled");
        assert_eq!(SkillOrigin::Agent.to_string(), "agent");
        assert_eq!(SkillOrigin::Hub.to_string(), "hub");
        assert_eq!(SkillOrigin::User.to_string(), "user");
    }

    #[test]
    fn skill_usage_new_defaults() {
        let usage = SkillUsage::new(SkillOrigin::Agent);
        assert_eq!(usage.state, SkillState::Active);
        assert_eq!(usage.created_by, SkillOrigin::Agent);
        assert_eq!(usage.use_count, 0);
        assert!(!usage.pinned);
    }

    #[test]
    fn consolidation_report_is_clean() {
        let report = ConsolidationReport {
            merge_candidates: vec![],
            skills_scanned: 5,
        };
        assert!(report.is_clean());
    }

    #[test]
    fn provenance_display() {
        assert_eq!(SkillProvenance::Bundled.to_string(), "bundled");
        assert_eq!(SkillProvenance::Agent.to_string(), "agent");
        assert_eq!(SkillProvenance::User.to_string(), "user");
    }

    #[test]
    fn provenance_serde_roundtrip() {
        for prov in [
            SkillProvenance::Bundled,
            SkillProvenance::Agent,
            SkillProvenance::User,
        ] {
            let json = serde_json::to_string(&prov).unwrap();
            let back: SkillProvenance = serde_json::from_str(&json).unwrap();
            assert_eq!(prov, back);
        }
    }

    #[test]
    fn usage_operation_serde_roundtrip() {
        for op in [
            UsageOperation::Create,
            UsageOperation::Edit,
            UsageOperation::Patch,
            UsageOperation::Delete,
        ] {
            let json = serde_json::to_string(&op).unwrap();
            let back: UsageOperation = serde_json::from_str(&json).unwrap();
            assert_eq!(op, back);
        }
    }

    #[test]
    fn skill_patch_default_is_all_none() {
        let patch = SkillPatch::default();
        assert!(patch.trigger_words.is_none());
        assert!(patch.description.is_none());
        assert!(patch.content.is_none());
    }

    #[test]
    fn usage_log_default_is_empty() {
        let log = SkillUsageLog::default();
        assert!(log.entries.is_empty());
    }
}
